package common

import com.badlogic.gdx.graphics.Color

//val scale: Float = 1f
const val TILE_SIZE: Int = 64
const val ROWS_SIZE = 14
const val COLUMNS_SIZE = 14
const val SCREEN_WIDTH = COLUMNS_SIZE * TILE_SIZE
const val SCREEN_HEIGHT = ROWS_SIZE * TILE_SIZE
val GAME_OVER_COLOR = Color(145 / 255f, 135 / 255f, 140 / 255f, 0.60f)

const val BASE_MAX_HP = 200f

val TOWER_RADIUS_COLOR = Color(40 / 255f, 210 / 255f, 255 / 255f, 0.40f)
val MODIFIER_PANE_BACKGROUND_COLOR = Color(250 / 255f, 160 / 255f, 60 / 255f, 0.80f)
val TOP_PANE_BACKGROUND_COLOR = Color(50 / 255f, 50 / 255f, 50 / 255f, 0.80f)

const val BASIC_TOWER_DEFAULT_DAMAGE = 50f
const val BASIC_TOWER_DEFAULT_ATTACK_SPEED = 0.5f
const val BASIC_TOWER_DEFAULT_RADIUS = 250f

const val BASIC_TOWER_DEFAULT_DAMAGE_MULTIPLIER = 1.1f
const val BASIC_TOWER_DEFAULT_ATTACK_SPEED_MULTIPLIER = 1.1f
const val BASIC_TOWER_DEFAULT_RADIUS_MULTIPLIER = 1.1f

const val DAMAGE_MODIFIER_DEFAULT_COST = 40
const val ATTACK_SPEED_MODIFIER_DEFAULT_COST = 50
const val RANGE_MODIFIER_DEFAULT_COST = 60

const val ARROW_DEFAULT_SPEED = 3f

const val SCORPION_DEFAULT_SPEED = 2f
const val SCORPION_DEFAULT_MAX_HP = 100f
const val SCORPION_DEFAULT_DAMAGE = 30f

const val INITIAL_CASH = 100
const val CASH_FROM_ENEMY = 10
const val COST_MULTIPLIER = 1.1f

const val RENDER_TIME = 10L
